# Tên của kịch bản
name: Fetch News RSS and Gold Price

# Lịch chạy: Chạy tự động 30 phút một lần
on:
  schedule:
    - cron: '*/30 * * * *'
  # Cho phép chạy thủ công (để test)
  workflow_dispatch:

# Các công việc cần làm
jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Bước 1: Tải code từ kho chứa của bạn về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Bước 3: Cài đặt các thư viện (thêm 2 thư viện mới)
      - name: Install dependencies
        run: |
          pip install feedparser
          pip install requests
          pip install beautifulsoup4

      # Bước 4A: Chạy script Python để tải tin tức RSS
      - name: Fetch and Parse RSS Categories
      
        # Sửa lỗi 'import: command not found'
        shell: python 
        
        run: |
          import feedparser
          import json
          import os

          CATEGORIES = {
              "tin-moi-nhat": "https://dantri.com.vn/rss/home.rss",
              "the-gioi": "https://dantri.com.vn/rss/the-gioi.rss",
              "the-thao": "https://dantri.com.vn/rss/the-thao.rss",
              "kinh-doanh": "https://dantri.com.vn/rss/kinh-doanh.rss",
              "xa-hoi": "https://dantri.com.vn/rss/xa-hoi.rss",
              "gia-vang": "https://bnews.vn/rss/gia-vang-32.rss",
              "chung-khoan": "https://thanhnien.vn/rss/kinh-te/chung-khoan.rss"
          }
          
          USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0"
          
          for filename_prefix, url in CATEGORIES.items():
              print(f"--- Fetching category: {filename_prefix} ---")
              feed = feedparser.parse(url, agent=USER_AGENT)
              
              articles = []
              if not feed.entries:
                  print(f"Error fetching {filename_prefix}.")
                  articles.append({"id": 1, "title": "Lỗi", "summary": "Không thể tải tin tức."})
              else:
                  for i, entry in enumerate(feed.entries[:3]):
                      articles.append({
                          "id": i + 1,
                          "title": entry.title,
                          "summary": entry.get('summary', entry.get('description', 'Không có nội dung chi tiết.'))
                      })
              
              json_output = {"articles": articles}
              output_filename = f"{filename_prefix}.json"
              with open(output_filename, 'w', encoding='utf-8') as f:
                  json.dump(json_output, f, ensure_ascii=False, indent=2)
              print(f"Created {output_filename}")
          
          print("All RSS files created successfully.")

      # Bước 4B: Chạy script Python để "cào" giá vàng SJC
      - name: Scrape SJC Gold Price
      
        # Sửa lỗi 'import: command not found'
        shell: python
        
        run: |
          import requests
          from bs4 import BeautifulSoup
          import json
          import re

          # Dùng link TRANG CHỦ (hoạt động)
          SJC_URL = "https://sjc.com.vn/"
          USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
          
          print(f"Scraping SJC Gold Price from {SJC_URL}...")
          
          try:
              # Tải trang web
              headers = {'User-Agent': USER_AGENT}
              response = requests.get(SJC_URL, headers=headers)
              response.raise_for_status() 
              
              soup = BeautifulSoup(response.text, 'html.parser')
              price_table = soup.find('div', id='price-hcm')
              sjc_row = price_table.find(lambda tag: tag.name == 'td' and 'SJC 1L, 10L' in tag.get_text())
              
              if sjc_row:
                  parent_row = sjc_row.find_parent('tr')
                  cells = parent_row.find_all('td')
                  buy_price = cells[1].get_text(strip=True)
                  sell_price = cells[2].get_text(strip=True)
                  
                  print(f"Found SJC 1L Price: Mua={buy_price}, Bán={sell_price}")
                  
                  summary = f"Giá vàng SJC 1 lượng, 10 lượng được niêm yết tại Hồ Chí Minh. Giá mua vào là {buy_price} triệu đồng. Giá bán ra là {sell_price} triệu đồng."
                  
                  json_output = {
                      "articles": [
                          {
                              "id": 1,
                              "title": f"Vàng SJC Mua: {buy_price} | Bán: {sell_price}",
                              "summary": summary
                          }
                      ]
                  }
              else:
                  print("Error: Could not find SJC 1L row in the HTML table.")
                  json_output = {"articles": [{"id": 1, "title": "Lỗi", "summary": "Không tìm thấy giá SJC 1L trong bảng."}]}

          except Exception as e:
              print(f"An error occurred during scraping: {e}")
              json_output = {"articles": [{"id": 1, "title": "Lỗi", "summary": f"Lỗi khi cào dữ liệu: {e}"}]}

          # Ghi ra file sjc.json
          with open('sjc.json', 'w', encoding='utf-8') as f:
              json.dump(json_output, f, ensure_ascii=False, indent=2)
          
          print("sjc.json file created successfully.")

      # Bước 5: Lưu TẤT CẢ CÁC file .json mới vào kho chứa
      - name: Commit and Push new .json files
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # *** DÒNG SỬA LỖI QUAN TRỌNG: ***
          # Kéo (pull) các thay đổi (nếu có) trước khi đẩy (push)
          git pull
          
          git add *.json
          git commit -m "Update news and SJC gold price (fixed git sync)" || echo "No changes to commit"
          git push
